# Generated by Django 5.2.4 on 2025-08-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('TICKETS_ACCESO_MENU', 'Puede acceder al módulo de Tickets')]},
        ),
    ]
