# Generated by Django 5.2.4 on 2025-07-14 15:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizaciones', '0001_initial'),
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usuario_ad', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_office', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_sap', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_a_cargo', models.TextField(blank=True, null=True)),
                ('impresora_a_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizaciones.area')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizaciones.cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('asland', 'Asland'), ('marsella', 'Marsella')], default='marsella', max_length=20)),
                ('tipo_solicitud', models.CharField(choices=[('nuevo_articulo', 'Nuevo Artículo'), ('produccion', 'Producción'), ('activacion', 'Activación'), ('modificacion', 'Modificación')], default='nuevo_articulo', max_length=20)),
                ('cotizacion', models.CharField(blank=True, choices=[('telefono', 'Por Teléfono'), ('documento', 'Por Documento'), ('lista_precios', 'Por Lista de Precios'), ('whatsapp', 'Por WhatsApp')], max_length=20, null=True)),
                ('archivo_cotizacion', models.FileField(blank=True, null=True, upload_to='cotizaciones/')),
                ('imagen_whatsapp', models.ImageField(blank=True, null=True, upload_to='cotizaciones/img/')),
                ('origen', models.CharField(choices=[('sin_origen', 'Sin origen'), ('nacional', 'Nacional'), ('importado', 'Importado'), ('mixto', 'Mixto')], default='sin_origen', max_length=20)),
                ('rut_proveedor', models.CharField(blank=True, max_length=12, null=True)),
                ('sku_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('creado', 'Código Creado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap.marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.proveedor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('udm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap.udm')),
            ],
        ),
    ]
