# Generated by Django 5.2.4 on 2025-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permisos_directos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_permiso_directo', to='permisos.permiso'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='movil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
