# Generated by Django 5.2.4 on 2025-07-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
        ('usuarios', '0002_solicitudcodigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcodigo',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='archivo_cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='cotizacion',
            field=models.CharField(blank=True, choices=[('telefono', 'Por Teléfono'), ('documento', 'Por Documento'), ('lista_precios', 'Por Lista de Precios'), ('whatsapp', 'Por WhatsApp')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='empresa',
            field=models.CharField(choices=[('asland', 'Asland'), ('marsella', 'Marsella')], default='marsella', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='imagen_whatsapp',
            field=models.ImageField(blank=True, null=True, upload_to='cotizaciones/img/'),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap.marca'),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='origen',
            field=models.CharField(choices=[('sin_origen', 'Sin origen'), ('nacional', 'Nacional'), ('importado', 'Importado'), ('mixto', 'Mixto')], default='sin_origen', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.proveedor'),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='rut_proveedor',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='sku_fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='sku_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='tipo_solicitud',
            field=models.CharField(choices=[('nuevo_articulo', 'Nuevo Artículo'), ('produccion', 'Producción'), ('activacion', 'Activación'), ('modificacion', 'Modificación')], default='nuevo_articulo', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='udm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap.udm'),
        ),
        migrations.AlterField(
            model_name='solicitudcodigo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcodigo',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
