# Generated by Django 5.2.4 on 2025-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_permisos_directos_alter_customuser_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcodigo',
            name='comentario_estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
