# Generated by Django 5.2.4 on 2025-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudcodigo_comentario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcodigo',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
