# Generated by Django 5.2.4 on 2025-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudcodigo_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecodigo',
            name='origen',
            field=models.CharField(choices=[('sin origen', 'Sin origen'), ('nacional', 'Nacional'), ('importado', 'Importado'), ('mixto', 'Mixto')], default='sin origen', max_length=20),
        ),
    ]
