# Generated by Django 5.2.4 on 2025-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudcodigo_comentario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='comentario_estado',
        ),
        migrations.AddField(
            model_name='solicitudcodigo',
            name='mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje al receptor'),
        ),
    ]
