# Generated by Django 5.2.4 on 2025-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_detallecodigo_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcodigo',
            name='codigo_extra',
            field=models.CharField(blank=True, choices=[('sin_sku', 'Sin SKU'), ('sin_codigo', 'Sin Código')], help_text='Solo se usa en solicitudes de tipo Activación', max_length=50, null=True),
        ),
    ]
