# Generated by Django 5.2.4 on 2025-07-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
        ('usuarios', '0004_remove_solicitudcodigo_comentario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sku_proveedor', models.CharField(max_length=100)),
                ('sku_fabricante', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sap.marca')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.solicitudcodigo')),
                ('udm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sap.udm')),
            ],
        ),
    ]
