# Generated by Django 5.2.4 on 2025-07-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
        ('usuarios', '0005_detallecodigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecodigo',
            name='origen',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('importado', 'Importado'), ('mixto', 'Mixto')], default='nacional', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecodigo',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='sap.proveedor'),
            preserve_default=False,
        ),
    ]
