# Generated by Django 5.2.4 on 2025-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_solicitudcodigo_codigo_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcodigo',
            name='codigo_extra',
            field=models.CharField(blank=True, help_text='Solo se usa en solicitudes de tipo Activación', max_length=50, null=True),
        ),
    ]
