# Generated by Django 5.2.4 on 2025-07-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_detallecodigo_origen_detallecodigo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='rut_proveedor',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='sku_fabricante',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='sku_proveedor',
        ),
        migrations.RemoveField(
            model_name='solicitudcodigo',
            name='udm',
        ),
    ]
