# Generated by Django 5.2.4 on 2025-07-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_solicitudcodigo_alto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('imagen', 'Imagen WhatsApp')], max_length=20)),
                ('archivo', models.FileField(upload_to='cotizaciones/')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='usuarios.solicitudcodigo')),
            ],
        ),
    ]
