# Generated by Django 5.2.4 on 2025-08-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.area')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.permiso')),
            ],
            options={
                'unique_together': {('area', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='PermisoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.cargo')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.permiso')),
            ],
            options={
                'unique_together': {('cargo', 'permiso')},
            },
        ),
    ]
